### ISSUE TITLE
Width in percentage on left column doesn't work as it should

### ISSUE THREAD

**Issue by sebasvanderplaat** [mendix/GridSelector#1]
Hi, 

When setting the property: width in percentage under Left data source, I expect that the complete column becomes wider and not only the left column on the top row. 

Also when i keep the value on 0, I expect that the text in the left column is visible. Now it just becomes invisible.

![image](https://cloud.githubusercontent.com/assets/12826863/8430631/c31fc932-1f2a-11e5-8d58-99081ead5d6e.png)

This is when the percentage is set to 25

![image](https://cloud.githubusercontent.com/assets/12826863/8430651/dc2ef7b8-1f2a-11e5-9a0e-1bdb655b1d82.png)

This is when the percentage is set to 0

**Comment by Rvthof** [comment]
Fixed in version 2.2. New version is pending on the App Store or you can download the .mpk directly here on Github.
